# Generated by Django 4.2.6 on 2023-10-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('RegionID', models.IntegerField()),
                ('SizeRank', models.IntegerField()),
                ('RegionName', models.CharField(max_length=50)),
                ('RegionType', models.CharField(max_length=50)),
                ('StateName', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Metro', models.CharField(max_length=250)),
                ('CountyName', models.CharField(max_length=250)),
                ('January', models.FloatField()),
                ('February', models.FloatField()),
                ('March', models.FloatField()),
                ('April', models.FloatField()),
                ('May', models.FloatField()),
                ('June', models.FloatField()),
                ('July', models.FloatField()),
                ('August', models.FloatField()),
                ('Septembe', models.FloatField()),
                ('October', models.FloatField()),
                ('November', models.FloatField()),
                ('December', models.FloatField()),
                ('Year', models.IntegerField()),
            ],
        ),
    ]
