# Generated by Django 4.2.6 on 2023-10-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_april_alter_city_august_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='April',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='August',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='December',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='February',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='January',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='July',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='June',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='March',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='May',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='November',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='October',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='Septembe',
            field=models.CharField(max_length=50),
        ),
    ]
