# Generated by Django 4.2.6 on 2023-10-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_alter_city_april_alter_city_august_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='CountyName',
        ),
        migrations.RemoveField(
            model_name='city',
            name='Metro',
        ),
        migrations.RemoveField(
            model_name='city',
            name='RegionType',
        ),
    ]
