# Generated by Django 4.2.6 on 2023-10-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_remove_city_countyname_remove_city_metro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='FipsCode',
            field=models.IntegerField(null=True),
        ),
    ]
