# Generated by Django 4.2.6 on 2023-10-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_city_fipscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='Average',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
