# Generated by Django 4.2.6 on 2023-10-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Bed', models.IntegerField()),
                ('Bath', models.IntegerField()),
                ('Acre_lot', models.FloatField()),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Zip_code', models.IntegerField()),
                ('House_size', models.FloatField()),
                ('Prev_sold_date', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Year', models.IntegerField()),
            ],
        ),
    ]
